### PR TITLE
Update Restoration

### PR DESCRIPTION
**Pull request by doadin**

### CODE REVIEW

**Comment by doadin** [comment]
Not ready:
I seem to be having an issue with talents[RO.BalanceAffinity] (or the other affinities) however other talent check works fine so not sure what up with that. Other than that not sure about the BalanceAffinity Eclipse logic.

**Comment by doadin** [comment]
@kaminaris @pwilkowski Any idea why its not picking up Affinity talents? For the moment I added a check just for form but obviously it would be more ideal if we could do it based on the affinity the player is.

**Comment by doadin** [comment]
interesting talents[RO.BalanceAffinity] is not working but print(MaxDps:HasTalent(197632)) returns 1 .

**Comment by pwilkowski** [comment]
As for talents I do not have active sub so I can't even check, maybe Id mismatch?

So is it ready to be merged?

**Comment by doadin** [comment]
its is not ready unless we want to just not support for Balance Affinity and no,the id is right, as I said print(MaxDps:HasTalent(197632)) returns 1 aka we have the talent. Unless thats not what it should return.

**Pull request merged**
